test cicd

diff --git a/.github/workflows/job_test_smoke.yaml b/.github/workflows/job_test_smoke.yaml
--- a/.github/workflows/job_test_smoke.yaml
+++ b/.github/workflows/job_test_smoke.yaml
@@ -2,78 +2,78 @@
 name: Smoke Testing
 
 on:
-    workflow_call:
-        inputs:
-            base_url:
-                description: "The base url"
-                required: true
-                type: string
-            env:
-                description: "Environment"
-                type: string
-                default: ca-central-1
+  workflow_call:
+    inputs:
+      base_url:
+        description: "The base url"
+        required: true
+        type: string
+      env:
+        description: "Environment"
+        type: string
+        default: ca-central-1
 
 jobs:
-    testing-smoke:
-        name: Smoke Testing
-        runs-on: ubuntu-latest
+  testing-smoke:
+    name: Smoke Testing ${{ inputs.env }}
+    runs-on: ubuntu-latest
+    env:
+      BASE_URL: ${{ inputs.base_url }}
+      K6_REPORT: k6/report/baseline_cicd_smoke.html
+      K6_SCRIPT: k6/script/test_smoke.js
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Wait for DNS
+        run: |
+          set -euo pipefail
+
+          ATTEMPT=120
+          URL_STATUS=0
+
+          for i in $(seq 1 $ATTEMPT); do
+            
+            echo "[$i] Try URL: $BASE_URL ..."
+            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $BASE_URL/api)
+            echo
+
+            if [ "$HTTP_CODE" -eq 307 ]; then
+              URL_STATUS=1
+              break
+            fi
+            echo "[$i] Retry..."
+            sleep 1
+          done
+
+          if [ $URL_STATUS -eq 0 ]; then
+            echo "URL fail: $BASE_URL"
+            exit 0
+          else
+            echo "URL success: $BASE_URL"
+          fi
+
+      - name: Setup K6
+        uses: grafana/setup-k6-action@v1
+
+      - name: Smoke Testing
+        id: testing-smoke
+        uses: grafana/run-k6-action@v1
         env:
-            BASE_URL: ${{ inputs.base_url }}
-            K6_REPORT: k6/report/baseline_cicd_smoke.html
-            K6_SCRIPT: k6/script/test_smoke.js
-        steps:
-            - name: Checkout
-              uses: actions/checkout@v4
+          K6_WEB_DASHBOARD: "true"
+          K6_WEB_DASHBOARD_EXPORT: "${{ env.K6_REPORT }}"
+        with:
+          debug: true
+          fail-fast: true
+          flags: --env BASE_URL=${{env.BASE_URL}}
+          path: |
+            ${{ env.K6_SCRIPT }}
 
-            - name: Wait for DNS
-              run: |
-                  set -euo pipefail
-
-                  ATTEMPT=120
-                  URL_STATUS=0
-
-                  for i in $(seq 1 $ATTEMPT); do
-                    
-                    echo "[$i] Try URL: $BASE_URL ..."
-                    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $BASE_URL/api)
-                    echo
-
-                    if [ "$HTTP_CODE" -eq 307 ]; then
-                      URL_STATUS=1
-                      break
-                    fi
-                    echo "[$i] Retry..."
-                    sleep 1
-                  done
-
-                  if [ $URL_STATUS -eq 0 ]; then
-                    echo "URL fail: $BASE_URL"
-                    exit 0
-                  else
-                    echo "URL success: $BASE_URL"
-                  fi
-
-            - name: Setup K6
-              uses: grafana/setup-k6-action@v1
-
-            - name: Smoke Testing
-              id: testing-smoke
-              uses: grafana/run-k6-action@v1
-              env:
-                  K6_WEB_DASHBOARD: "true"
-                  K6_WEB_DASHBOARD_EXPORT: "${{ env.K6_REPORT }}"
-              with:
-                  debug: true
-                  fail-fast: true
-                  flags: --env BASE_URL=${{env.BASE_URL}}
-                  path: |
-                      ${{ env.K6_SCRIPT }}
-
-            - name: Upload smoke report artifact
-              if: always()
-              uses: actions/upload-artifact@v4
-              with:
-                  name: "k6-report-smoke-${{ inputs.env }}"
-                  path: |
-                      ${{ env.K6_REPORT }}
-                  retention-days: 7
+      - name: Upload smoke report artifact
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: "k6-report-smoke-${{ inputs.env }}"
+          path: |
+            ${{ env.K6_REPORT }}
+          retention-days: 7
